# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'historia-del-cine'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-K1CHGHX488'

menu:
  - name: Inicio
    link: /
  - name: Buscador
    link: /Buscador/
  - name: Películas
    link: /peliculas/
  - name: Directores
    link: /directores/
  - name: Artículos
    link: /
  - name: Etiquetas
    link: /tags/
