# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'historiadelcine'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-XMMQ0JWLPC'

menu:
  - name: Inicio
    link: /
  - name: Buscador
    link: /Buscador/
  - name: Peliculas
    link: /Peliculas/
  - name: Artículos
    link: /
  - name: Etiquetas
    link: /tags/
